<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="salesforce"
    errors="1" failures="0" hostname="" id="" package="salesforce" skipped="0"
    tests="1" time="0.003000" timestamp="Wed, 07 Nov 2018 18:47:44 GMT">
  
    <testcase name="Salesforce Test" classname="salesforce" time="0.003000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Salesforce / Salesforce Test]:

  ReferenceError: username is not defined
    at Object.Salesforce Test (C:\Users\jackson.gunther\projects\seleniumTest\apiTest\tests\salesforce.js:11:40)
    at Module.call (C:\Users\jackson.gunther\projects\seleniumTest\apiTest\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\jackson.gunther\projects\seleniumTest\apiTest\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\jackson.gunther\projects\seleniumTest\apiTest\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\jackson.gunther\projects\seleniumTest\apiTest\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\jackson.gunther\projects\seleniumTest\apiTest\node_modules\q\q.js:796:13)
    at C:\Users\jackson.gunther\projects\seleniumTest\apiTest\node_modules\q\q.js:556:49
    at runSingle (C:\Users\jackson.gunther\projects\seleniumTest\apiTest\node_modules\q\q.js:137:13)
    at flush (C:\Users\jackson.gunther\projects\seleniumTest\apiTest\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
